disabled = false
languageCode = "en"
languageName = "English"
weight = 2
title = "Seoul to Paris"
contentDir = "content/en"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

# [params.author]
#   name = "Your name"
#   email = "youremail@example.com"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
#   headline = "I'm only human"
#   bio = "A little about you"
#   links = [
#     { email = "mailto:hello@your_domain.com" },
#     { github = "https://github.com/username" },
#   ]
